const PDFDocument = require('pdfkit');

exports.generateInvoicePDF = (invoice) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers = [];
    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    const company = {
      name: process.env.COMPANY_NAME || 'Your Company',
      email: process.env.COMPANY_EMAIL || '',
      phone: process.env.COMPANY_PHONE || '',
      address: process.env.COMPANY_ADDRESS || '',
    };

    // Header
    doc.fontSize(24).font('Helvetica-Bold').fillColor('#1e40af').text(company.name, 50, 50);
    doc.fontSize(9).font('Helvetica').fillColor('#6b7280')
      .text(company.address, 50, 80)
      .text(`${company.phone} | ${company.email}`, 50, 92);

    // Invoice title
    doc.fontSize(28).font('Helvetica-Bold').fillColor('#111827').text('INVOICE', 400, 50, { align: 'right' });
    doc.fontSize(10).font('Helvetica').fillColor('#6b7280')
      .text(`Invoice #: ${invoice.invoice_number}`, 400, 85, { align: 'right' })
      .text(`Date: ${new Date(invoice.created_at).toLocaleDateString()}`, 400, 100, { align: 'right' })
      .text(`Due: ${invoice.due_date ? new Date(invoice.due_date).toLocaleDateString() : 'N/A'}`, 400, 115, { align: 'right' });

    // Status badge
    const statusColors = { paid: '#16a34a', draft: '#d97706', overdue: '#dc2626', sent: '#2563eb', cancelled: '#6b7280' };
    doc.roundedRect(400, 130, 140, 22, 4).fill(statusColors[invoice.status] || '#6b7280');
    doc.fontSize(10).font('Helvetica-Bold').fillColor('white').text(invoice.status.toUpperCase(), 400, 135, { width: 140, align: 'center' });

    // Divider
    doc.moveTo(50, 165).lineTo(545, 165).strokeColor('#e5e7eb').lineWidth(1).stroke();

    // Bill To
    doc.fontSize(10).font('Helvetica-Bold').fillColor('#374151').text('BILL TO:', 50, 180);
    doc.fontSize(11).font('Helvetica-Bold').fillColor('#111827').text(invoice.customer?.name || '', 50, 195);
    doc.fontSize(9).font('Helvetica').fillColor('#6b7280')
      .text(invoice.customer?.email || '', 50, 210)
      .text(invoice.customer?.phone || '', 50, 222)
      .text(invoice.customer?.address || '', 50, 234);

    // Items table header
    const tableTop = 270;
    doc.rect(50, tableTop, 495, 22).fill('#1e40af');
    doc.fontSize(9).font('Helvetica-Bold').fillColor('white')
      .text('ITEM', 60, tableTop + 7)
      .text('QTY', 310, tableTop + 7, { width: 50, align: 'center' })
      .text('UNIT PRICE', 360, tableTop + 7, { width: 80, align: 'right' })
      .text('TOTAL', 460, tableTop + 7, { width: 75, align: 'right' });

    // Items
    const items = invoice.order?.items || [];
    let y = tableTop + 22;
    items.forEach((item, i) => {
      if (i % 2 === 0) doc.rect(50, y, 495, 20).fill('#f9fafb');
      doc.fontSize(9).font('Helvetica').fillColor('#111827')
        .text(item.product_name || item.product?.name || '', 60, y + 6, { width: 240 })
        .text(item.quantity, 310, y + 6, { width: 50, align: 'center' })
        .text(`₦${parseFloat(item.unit_price).toLocaleString()}`, 360, y + 6, { width: 80, align: 'right' })
        .text(`₦${parseFloat(item.total).toLocaleString()}`, 460, y + 6, { width: 75, align: 'right' });
      y += 20;
    });

    // Totals
    y += 15;
    doc.moveTo(350, y).lineTo(545, y).strokeColor('#e5e7eb').stroke();
    y += 10;

    const addRow = (label, value, bold = false) => {
      doc.fontSize(10).font(bold ? 'Helvetica-Bold' : 'Helvetica').fillColor(bold ? '#111827' : '#6b7280')
        .text(label, 350, y).text(value, 460, y, { width: 75, align: 'right' });
      y += 18;
    };

    addRow('Subtotal:', `₦${parseFloat(invoice.subtotal || 0).toLocaleString()}`);
    if (invoice.discount_amount > 0) addRow('Discount:', `-₦${parseFloat(invoice.discount_amount).toLocaleString()}`);
    if (invoice.tax_amount > 0) addRow('Tax:', `₦${parseFloat(invoice.tax_amount).toLocaleString()}`);
    doc.moveTo(350, y).lineTo(545, y).strokeColor('#1e40af').lineWidth(2).stroke();
    y += 8;
    addRow('TOTAL:', `₦${parseFloat(invoice.total_amount || 0).toLocaleString()}`, true);
    if (invoice.amount_paid > 0) addRow('Paid:', `₦${parseFloat(invoice.amount_paid).toLocaleString()}`);
    if (invoice.balance_due > 0) addRow('Balance Due:', `₦${parseFloat(invoice.balance_due).toLocaleString()}`, true);

    // Footer
    doc.fontSize(8).font('Helvetica').fillColor('#9ca3af')
      .text('Thank you for your business!', 50, 750, { align: 'center', width: 495 })
      .text(`Generated by ${company.name} | ${new Date().toLocaleString()}`, 50, 762, { align: 'center', width: 495 });

    doc.end();
  });
};
